### ISSUE TITLE
fatal: dumb http transport does not support shallow capabilities

### ISSUE THREAD

**Issue by djangoliv** [sidhartharya10/emacsit#1]
Hello,

I have been looking for a simple package manager for a while so thank you for sharing your package, it seems very interesting.

So first issue for you :-) Sometimes you can't use `git clone --depth=1`. 
Example:  `https://git.deparis.io/flycheck-grammalecte`

Do you think you can support this case ?

Regards

**Comment by SidharthArya** [comment]
@djangoliv  I have added the support for this. https://github.com/SidharthArya/emacsit/commit/f1b222a53de2e6c47280132e0808caee60fc1e07
Thank you for the first issue. :P
By the way, if you are looking for something similar to this, Try:
https://github.com/raxod502/straight.el

**Comment by djangoliv** [comment]
thanks it works. 
Straight is very big. Not as simple as yours.
